# Schema for the configuration files of the newTheme theme.
newtheme.settings:
  type: theme_settings
  label: 'newTheme settings'
  mapping:
    font_size:
      type: integer
      label: Font size
